name: Python application CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # Exclude the site-packages and any other directories not relevant to your linting
        flake8 . --count --exclude=venv,fastapi/lib/python3.9/site-packages --select=E9,F63,F7,F82 --show-source --statistics --max-line-length=127
        if [ $? -ne 0 ]; then
          echo "Flake8 found errors."
          exit 1
        fi


    - name: Run tests with pytest
      run: |
        pytest
        if [ $? -ne 0 ]; then
          echo "Tests failed."
          exit 1
        fi



      
